(function($){$(function(){var margin_width=($(window).width()-1180)/2;margin_page_left='-'+margin_width+'px';padding_page_left=margin_width+'px';width_page=$(window).width()-margin_width+'px';$('.catalog_nav_links .menu_3').css({'width':width_page,'margin-left':margin_page_left,'padding-left':padding_page_left});


if($('.tab_blocks_scroll ').length>0){$(".tab_blocks_scroll").mCustomScrollbar({theme:"minimal"});}var connector=function(itemNavigation,carouselStage){return carouselStage.jcarousel('items').eq(itemNavigation.index());};var carouselStage=$('.lt_column_slider_block').jcarousel();var carouselNavigation;if($(window).width()>=1240){carouselNavigation=$('.lt_column_slider_nav').jcarousel({vertical:true});}else{carouselNavigation=$('.lt_column_slider_nav').jcarousel();$(' .lt_column_slider_block li').swipe({swipeLeft:function(event,direction,distance,duration,fingerCount,fingerData){$('.lt_column_slider_block ').jcarousel('scroll','+=1');},swipeRight:function(event,direction,distance,duration,fingerCount,fingerData){$('.lt_column_slider_block ').jcarousel('scroll','-=1');},tap:function(event,target){$('.lt_column_slider_block ').jcarousel('scroll','+=1');}});}carouselNavigation.jcarousel('items').each(function(){var item=$(this);var target=connector(item,carouselStage);item.on('jcarouselcontrol:active',function(){carouselNavigation.jcarousel('scrollIntoView',this);item.addClass('active');}).on('jcarouselcontrol:inactive',function(){item.removeClass('active');}).jcarouselControl({target:target,carousel:carouselStage});});$('.prev-stage').on('jcarouselcontrol:inactive',function(){$(this).addClass('inactive');}).on('jcarouselcontrol:active',function(){$(this).removeClass('inactive');}).jcarouselControl({target:'-=1'});$('.next-stage').on('jcarouselcontrol:inactive',function(){$(this).addClass('inactive');}).on('jcarouselcontrol:active',function(){$(this).removeClass('inactive');}).jcarouselControl({target:'+=1'});$('.prev-navigation').on('jcarouselcontrol:inactive',function(){$(this).addClass('inactive');}).on('jcarouselcontrol:active',function(){$(this).removeClass('inactive');}).jcarouselControl({target:'-=1'});$('.next-navigation').on('jcarouselcontrol:inactive',function(){$(this).addClass('inactive');}).on('jcarouselcontrol:active',function(){$(this).removeClass('inactive');}).jcarouselControl({target:'+=1'});if($('.card_top_links_slider').length>0){$('.card_top_links_slider').jcarousel({scroll:1,wrap:'both'});}if($(window).width()<=1240){if($('.tab_blocks .tab_links_slider').length>0){carouselNavigation=$('.tab_blocks .tab_links_slider').jcarousel({scroll:1,wrap:'both'});}}$('.jcarousel-control-prev').on('jcarouselcontrol:active',function(){$(this).removeClass('inactive');}).on('jcarouselcontrol:inactive',function(){$(this).addClass('inactive');}).jcarouselControl({target:'-=1'});$('.jcarousel-control-next').on('jcarouselcontrol:active',function(){$(this).removeClass('inactive');}).on('jcarouselcontrol:inactive',function(){$(this).addClass('inactive');}).jcarouselControl({target:'+=1'});


	$('.rt_description_info').hover(function(){
		$('.price_desc').addClass('act');
	},function(){	
		$('.price_desc').removeClass('act');
	});
	
	
});
})(jQuery);
function show_reviews(){$('.hide_review').show();$('#show_reviews').remove();}   